#!/usr/bin/with-contenv bash

echo "**** installing php8 and composer ****"
apt-get install -y \
  composer \
  php8.0

echo "**** installing php8 modules ****"
apt install php-xml
apt-get install php-curl
