#!/usr/bin/with-contenv bash

echo "**** Download Composer ****"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

echo "**** Installing local composer  ****"
php composer-setup.php

echo "**** Clear composer setup ****"
php -r "unlink('composer-setup.php');"

echo "**** Global composer install  ****"
sudo mv composer.phar /usr/local/bin/composer